language: python
python:
  - "2.7"
  - "pypy"

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-twisted.txt

# run tests without beanstalkd until Travis has it
script: make test-without-beanstalkd
